/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Icon: typeof import('./../components/Icon/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./../components/Icon/SvgIcon.vue')['default']
    SvgRaw: typeof import('./../components/Icon/SvgRaw.vue')['default']
    SvgRaw222: typeof import('./../components/Icon/SvgRaw222.vue')['default']
    SvgRawPro: typeof import('./../components/Icon/SvgRawPro.vue')['default']
  }
}
